package models

//DefaultResponseObject is the standard handler for all non model responces.
type DefaultResponseObject struct {
	Code    int    `json:"code"`
	Message string `json:"message,omitempty"`
}

//BuildResponse is a one liner to build a DefaultResponseObject struct
func BuildResponse(code int, m string) *DefaultResponseObject {
	toReturn := DefaultResponseObject{}
	toReturn.Code = code
	toReturn.Message = m
	return &toReturn
}

///
// Univeral Structs
///

var MimeTypes = map[string][]string{
	"text/h323":                               []string{".323"},
	"application/internet-property-stream":    []string{".acx"},
	"audio/x-aiff":                            []string{".aif", ".aifc", ".aiff"},
	"video/x-ms-asf":                          []string{".asf", ".asr", ".asx"},
	"video/x-msvideo":                         []string{".avi"},
	"application/olescript":                   []string{".axs"},
	"text/plain":                              []string{".txt", ".bas", ".c", ".h"},
	"application/x-bcpio":                     []string{".bcpio"},
	"image/bmp":                               []string{".bmp"},
	"application/vnd.ms-pkiseccat":            []string{".cat"},
	"application/x-cdf":                       []string{".cdf"},
	"application/x-netcdf":                    []string{".cdf", ".nc"},
	"application/x-x509-ca-cert":              []string{".crt", ".cer", ".der"},
	"application/x-msclip":                    []string{".clp"},
	"image/x-cmx":                             []string{".cmx"},
	"image/cis-cod":                           []string{".cod"},
	"application/x-cpio":                      []string{".cpio"},
	"application/x-mscardfile":                []string{".crd"},
	"application/pkix-crl":                    []string{".crl"},
	"application/x-csh":                       []string{".csh"},
	"text/css":                                []string{".css"},
	"application/x-director":                  []string{".dcr", ".dir", ".drx"},
	"application/x-msdownload":                []string{".dll"},
	"application/octet-stream":                []string{".bin", ".class", ".dms", ".*", ".exe", ".lha", ".lzh"},
	"application/msword":                      []string{".doc", ".dot"},
	"application/x-dvi":                       []string{".dvi"},
	"application/postscript":                  []string{".ps", ".eps", ".ai"},
	"text/x-setext":                           []string{".etx"},
	"application/envoy":                       []string{".evy"},
	"application/fractals":                    []string{".fif"},
	"image/gif":                               []string{".gif"},
	"application/x-gtar":                      []string{".gtar"},
	"application/x-gzip":                      []string{".gz"},
	"application/x-hdf":                       []string{".hdf"},
	"application/winhlp":                      []string{".hlp"},
	"application/mac-binhex40":                []string{".hqx"},
	"application/hta":                         []string{".hta"},
	"text/x-component":                        []string{".htc"},
	"text/html":                               []string{".html", ".htm", ".stml"},
	"text/webviewhtml":                        []string{".htt"},
	"image/x-icon":                            []string{".ico"},
	"image/ief":                               []string{".ief"},
	"application/x-iphone":                    []string{".iii"},
	"application/x-internet-signup":           []string{".ins", ".isp"},
	"image/pipeg":                             []string{".jfif"},
	"image/jpeg":                              []string{".jpg", ".jpeg", ".jpe"},
	"application/x-javascript":                []string{".js"},
	"application/x-latex":                     []string{".latex"},
	"video/x-la-asf":                          []string{".lsf", ".lsx"},
	"application/x-msmediaview":               []string{".m13", ".m14", ".mvb"},
	"audio/x-mpegurl":                         []string{".m3u"},
	"application/x-troff-man":                 []string{".man"},
	"application/x-msaccess":                  []string{".mdb"},
	"application/x-troff-me":                  []string{".me"},
	"message/rfc822":                          []string{".mht", ".mhtml", ".nws"},
	"audio/mid":                               []string{".mid", ".rmi"},
	"application/x-msmoney":                   []string{".mny"},
	"video/quicktime":                         []string{".mov", ".qt"},
	"video/x-sgi-movie":                       []string{".movie"},
	"video/mpeg":                              []string{".mpg", ".mp2", ".mp3", ".mpa", ".mpe", ".mpeg", ".mpv2"},
	"application/vnd.ms-project":              []string{".mpp"},
	"application/x-troff-ms":                  []string{".ms"},
	"application/vnd.ms-outlook":              []string{".msg"},
	"application/oda":                         []string{".oda"},
	"application/pkcs10":                      []string{".p10"},
	"application/x-pkcs12":                    []string{".p12", ".pfx"},
	"application/x-pkcs7-certificates":        []string{".p7b", ".spc"},
	"application/x-pkcs7-mime":                []string{".p7c", ".p7m"},
	"application/x-pkcs7-certreqresp":         []string{".p7r"},
	"application/x-pkcs7-signature":           []string{".p7s"},
	"image/x-portable-bitmap":                 []string{".pbm"},
	"application/pdf":                         []string{".pdf"},
	"image/x-portable-graymap":                []string{".pgm"},
	"application/ynd.ms-pkipko":               []string{".pko"},
	"application/x-perfmon":                   []string{".pma", ".pmc", ".pml", ".pmr", ".pmw"},
	"image/x-portable-anymap":                 []string{".pnm"},
	"image/x-portable-pixmap":                 []string{".ppm"},
	"application/vnd.ms-powerpoint":           []string{".ppt", ".pps", ".pot"},
	"application/pics-rules":                  []string{".prf"},
	"application/x-mspublisher":               []string{".pub"},
	"audio/x-pn-realaudio":                    []string{".ra", ".ram"},
	"image/x-cmu-raster":                      []string{".ras"},
	"image/x-rgb":                             []string{".rgb"},
	"application/rtf":                         []string{".rtf"},
	"text/richtext":                           []string{".rtx"},
	"application/x-msschedule":                []string{".scd"},
	"text/scriptlet":                          []string{".sct"},
	"application/set-payment-initiation":      []string{".setpay"},
	"application/set-registration-initiation": []string{".setreg"},
	"application/x-sh":                        []string{".sh"},
	"application/x-shar":                      []string{".shar"},
	"application/x-stuffit":                   []string{".sit"},
	"audio/basic":                             []string{".snd", ".au"},
	"application/futuresplash":                []string{".spl"},
	"application/x-wais-source":               []string{".src"},
	"application/vnd.ms-pkicertstore":         []string{".sst"},
	"application/vnd.ms-pkistl":               []string{".stl"},
	"application/x-sv4cpio":                   []string{".sv4cpio"},
	"application/x-sv4crc":                    []string{".sv4crc"},
	"image/svg+xml":                           []string{".svg"},
	"application/x-shockwave-flash":           []string{".swf"},
	"application/x-tar":                       []string{".tar"},
	"application/x-tcl":                       []string{".tcl"},
	"application/x-tex":                       []string{".tex"},
	"application/x-texinfo":                   []string{".texinfo", ".texi"},
	"application/x-compressed":                []string{".tgz"},
	"image/tiff":                              []string{".tiff", ".tif"},
	"application/x-troff":                     []string{".tr", ".roff", ".t"},
	"application/x-msterminal":                []string{".trm"},
	"text/tab-separated-values":               []string{".tsv"},
	"text/iuls":                               []string{".uls"},
	"application/x-ustar":                     []string{".ustar"},
	"text/x-vcard":                            []string{".vcf"},
	"audio/x-wav":                             []string{".wav"},
	"application/vnd.ms-works":                []string{".wps", ".wcm", ".wdb", ".wks"},
	"application/x-msmetafile":                []string{".wmf"},
	"application/x-mswrite":                   []string{".wri"},
	"x-world/x-vrml":                          []string{".wrl", ".wrz", ".xaf", ".xof", ".vrml", ".flr"},
	"image/x-xbitmap":                         []string{".xbm"},
	"application/vnd.ms-excel":                []string{".xls", ".xlc", ".xlm", ".xla", ".xlt", ".xlw"},
	"image/x-xpixmap":                         []string{".xpm"},
	"image/x-xwindowdump":                     []string{".xwd"},
	"application/x-compress":                  []string{".z"},
	"application/zip":                         []string{".zip"},
}
